# Generated by Django 5.1.5 on 2025-01-24 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('eyecolor', models.CharField(choices=[('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('gray', 'Gray'), ('heterochromia', 'Heterochromia')], default='brown', max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('is_adopted', models.BooleanField(default=False)),
                ('original_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petflix.pet')),
                ('breed', models.CharField(choices=[('persian', 'Persian'), ('siamese', 'Siamese'), ('mainecoon', 'Maine Coon'), ('ragdoll', 'Ragdoll'), ('bengal', 'Bengal'), ('sphynx', 'Sphynx'), ('undefined', 'Undefined')], default='undefined', max_length=20)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('orange', 'Orange'), ('brown', 'Brown'), ('multi', 'Multi'), ('undefined', 'Undefined')], default='undefined', max_length=20)),
            ],
            bases=('petflix.pet',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petflix.pet')),
                ('breed', models.CharField(choices=[('labrador', 'Labrador'), ('beagle', 'Beagle'), ('bulldog', 'Bulldog'), ('poodle', 'Poodle'), ('germanshepherd', 'German Shepherd'), ('goldenretriever', 'Golden Retriever'), ('undefined', 'Undefined')], default='undefined', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('undefined', 'Undefined')], default='undefined', max_length=20)),
            ],
            bases=('petflix.pet',),
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petflix.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetAdoption',
            fields=[
            ],
            options={
                'ordering': ['created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('petflix.pet',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
