# Generated by Django 5.1.5 on 2025-01-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], default='dog', max_length=20),
        ),
    ]
