# Generated by Django 5.1.5 on 2025-01-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petflix', '0003_alter_pet_original_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default='pet', max_length=30, unique=True),
        ),
    ]
